app.title=User Feedback(local)
# Enable related features.
spring.cloud.azure.active-directory.enabled=true

# Specifies your Active Directory ID:
spring.cloud.azure.active-directory.profile.tenant-id=6fe7e4ab-29ef-42c6-953b-0f8aaa49db29

# Specifies your App Registration's Application ID:
spring.cloud.azure.active-directory.credential.client-id=592a48d6-7ce2-4d17-a9e1-03bd0d8ed127

# Specifies your App Registration's secret key:
spring.cloud.azure.active-directory.credential.client-secret=x~c8Q~aGjXlA-3FyD2kwP5uzWdB9iNN9XFaMtbx~